### ISSUE TITLE
v7.0.0：アップデート内容まとめ

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#166]
膨大になってきたv7.0.0のアップデート内容と、旧バージョンからの移行方法をまとめておく。

v7.0.0はドキュメント整備などを含め2019年内の正式リリースを目指す。それまではnpmにalpha版として公開していく。実務・自前制作で検証。正式リリースまでは変数など根本的な変更なども大胆に行い、ドキュメント更新が間に合わないため、通常の `npm install` ではv6.6.0をインストールさせる仕様にする。

## Demo

- URL：https://musubii-debug.netlify.com/

## Install (v7.0.0-Alpha-*)

```bash
$ npm install musubii@next
```

### Total

- [x] SCSSカスタマイズの再設計 #163 
- [x] SCSSで出力管理・デフォルトの最小限化 #201
- [x] SCSS：CSS Variables適応機能を追加 #148
- [x] SCSS：ダークテーマを実装 #165 
- [x] IE対応を非推奨項目に設定 #194 
- [x] MIXTONEの色を反映 #145 

### Addition

- [x] Grid：Gapのバリュエーションを追加 #162
- [x] Grid：Baseline並びの追加 #144 
- [x] Box：ボックスレイアウトの追加 #169 
- [x] Card：カードレイアウトの追加 #170 
- [x] Joint：Buttons・Badge・Formの結合Classを追加 #167
- [x] Text：Line Height調整用のClassを追加 #195 
- [x] Text：リンク下線をunderlineに変更する設定を追加 #224
- [x] Button：遷移を示す角の追加 #172
- [x] Button：正方形スタイルを追加 #210
- [x] Button：Info・Warningスタイルの利用 #143
- [x] Button：フォーカスリングをCSSで設定 #154
- [x] Badge：バッジモジュールを追加 #182 
- [x] Form：Inputにプレーンスタイルを追加 #189
- [x] Form：Inputにアンダーラインスタイルを追加 #190
- [x] Form：Inputにインサイドスタイルを追加 #204
- [x] Form：Inputのバリデーションカラーを追加 #193
- [x] Form：Radio・CheckboxをCSSに置き換え #149 
- [x] Form：フォーカスリングをCSSで設定 #155 
- [x] Table：thの線幅を調整できるオプションを追加 #215
- [x] iframe：アスペクト比を維持するClassを追加 #112 
- [x] Alert：吹き出し状に変化させられるオプションを追加 #130
- [x] WYSIWYG：定義リストの追加 #126
- [x] WYSIWYG：figure・figcaptionの追加 #134
- [x] WYSIWYG：リンクリバースの設定を追加 #147 
- [x] Display：hidden化Classの追加 #179 
- [x] Space：Spaceのバリュエーションを追加 #161 
- [x] Margin：マージンを付与できるUtilityを追加 #187
- [x] Padding：パディングを付与できるUtilityを追加 #176 
- [x] Overflow：スクロール等のUtilityを分離して追加 #199

### Changes

- [x] Variable：変数名のDefaultを削除 #205
- [x] Variable：いくつかの初期値をpxに変更 #174
- [x] Variable：テーマカラー変数のSass Dashi依存を解除 #160
- [x] Section：Inner PaddingをUtilityに分離 #173 
- [x] Section：Inner Softの廃止 #183
- [x] Grid：デフォルトのGapをゼロに変更 #168
- [x] Grid：カラムのClass名をcolからcolumnに変更 #157 
- [x] Heading：廃止してファイルを削除 #200
- [x] Text：Texts Classの廃止 #197
- [x] Text：Deco対象をテキストに限定 #158
- [x] Button：ボタンのClass名をbtnからbuttonに変更 #156
- [x] Button：非活性のクラス名・変数名の変更 #132
- [x] Button：非活性の場合にイベントを封印 #221
- [x] Button：Ghostスタイルの廃止 #203
- [x] Button：Buttonsを廃止・マージンはSpaceに分離 #186
- [x] Button：Bar設定をLayout Classに分離 #177 
- [x] Form：Fieldを廃止・マージンはSpaceに分離 #185
- [x] Form：Bar設定をLayout Classに分離 #178
- [x] Icon：隣接Textと付与し合うマージンを削除 #184 
- [x] Deco：ファイルを削除（内容はテキスト等へ移動） #198
- [x] Space：ファイルをLayoutからUtilityに移動 #196
- [x] Space：要素によるマージン変化を削除 #175

### Bugfix

- [x] Button：天地中央寄せにできない不具合を修正 #209
- [x] Button：OutlineのDisabledスタイルを修正 #214
- [x] Form：SelectのIE表示バグ解消 #151
- [x] Form：Selectのカーソル表現を修正 #150
- [x] Icon：SVG版にも色・サイズを適応 #180 
- [x] Flex：IEで段落ちするバグを修正 #152

## Cancelled

- ~~単位のremを再検討~~ #146
- ~~Build：CSS Variables版ファイルを別途ビルド~~ #164
- ~~Grid：CSS Gridを使った実装~~ #153 
- ~~Flex：Flexbox化Layout Classの追加~~ #171 
- ~~Flex：ファイルをUtilityからLayoutに移動~~ #188
- ~~Form：Inputへのアイコン設置機能を追加~~ #191 
- ~~Form：内側シャドウ・枠線をClassで分離~~ #192
- ~~Form：Multiple Selectに選択済み背景色を追加~~ #206

## Migration

- v6.6.0 → v7.0.0-alpha.42 #238

**Comment by qrac** [comment]
v7.0.0 正式版用

## Update

### Total

- [x] SCSSカスタマイズの再設計 #163 
- [x] SCSSで出力管理・デフォルトの最小限化 #201
- [x] SCSS：CSS Variables適応機能を追加 #148
- [x] SCSS：ダークテーマを実装 #165 
- [x] IE対応を非推奨項目に設定 #194 
- [x] MIXTONEの色を反映 #145 

### Addition

- [x] Grid：Gapのバリュエーションを追加 #162
- [x] Grid：Baseline並びの追加 #144 
- [x] Box：ボックスレイアウトの追加 #169 
- [x] Card：カードレイアウトの追加 #170 
- [x] Joint：Buttons・Badge・Formの結合Classを追加 #167
- [x] Text：Line Height調整用のClassを追加 #195 
- [x] Text：リンク下線をunderlineに変更する設定を追加 #224
- [x] Button：遷移を示す角の追加 #172
- [x] Button：正方形スタイルを追加 #210
- [x] Button：Info・Warningスタイルの利用 #143
- [x] Button：フォーカスリングをCSSで設定 #154
- [x] Badge：バッジモジュールを追加 #182 
- [x] Form：Inputにプレーンスタイルを追加 #189
- [x] Form：Inputにアンダーラインスタイルを追加 #190
- [x] Form：Inputにインサイドスタイルを追加 #204
- [x] Form：Inputのバリデーションカラーを追加 #193
- [x] Form：Radio・CheckboxをCSSに置き換え #149 
- [x] Form：フォーカスリングをCSSで設定 #155 
- [x] Table：thの線幅を調整できるオプションを追加 #215
- [x] iframe：アスペクト比を維持するClassを追加 #112 
- [x] Alert：吹き出し状に変化させられるオプションを追加 #130
- [x] WYSIWYG：定義リストの追加 #126
- [x] WYSIWYG：figure・figcaptionの追加 #134
- [x] WYSIWYG：リンクリバースの設定を追加 #147 
- [x] Display：hidden化Classの追加 #179 
- [x] Space：Spaceのバリュエーションを追加 #161 
- [x] Margin：マージンを付与できるUtilityを追加 #187
- [x] Padding：パディングを付与できるUtilityを追加 #176 
- [x] Overflow：スクロール等のUtilityを分離して追加 #199

### Changes

- [x] Variable：変数名のDefaultを削除 #205
- [x] Variable：いくつかの初期値をpxに変更 #174
- [x] Variable：テーマカラー変数のSass Dashi依存を解除 #160
- [x] Section：Inner PaddingをUtilityに分離 #173 
- [x] Section：Inner Softの廃止 #183
- [x] Grid：デフォルトのGapをゼロに変更 #168
- [x] Grid：カラムのClass名をcolからcolumnに変更 #157 
- [x] Heading：廃止してファイルを削除 #200
- [x] Text：Texts Classの廃止 #197
- [x] Text：Deco対象をテキストに限定 #158
- [x] Button：ボタンのClass名をbtnからbuttonに変更 #156
- [x] Button：非活性のクラス名・変数名の変更 #132
- [x] Button：非活性の場合にイベントを封印 #221
- [x] Button：Ghostスタイルの廃止 #203
- [x] Button：Buttonsを廃止・マージンはSpaceに分離 #186
- [x] Button：Bar設定をLayout Classに分離 #177 
- [x] Form：Fieldを廃止・マージンはSpaceに分離 #185
- [x] Form：Bar設定をLayout Classに分離 #178
- [x] Icon：隣接Textと付与し合うマージンを削除 #184 
- [x] Deco：ファイルを削除（内容はテキスト等へ移動） #198
- [x] Space：ファイルをLayoutからUtilityに移動 #196
- [x] Space：要素によるマージン変化を削除 #175

### Bugfix

- [x] Button：天地中央寄せにできない不具合を修正 #209
- [x] Button：OutlineのDisabledスタイルを修正 #214
- [x] Form：SelectのIE表示バグ解消 #151
- [x] Form：Selectのカーソル表現を修正 #150
- [x] Icon：SVG版にも色・サイズを適応 #180 
- [x] Flex：IEで段落ちするバグを修正 #152

## Cancelled

- ~~単位のremを再検討~~ #146
- ~~Build：CSS Variables版ファイルを別途ビルド~~ #164
- ~~Grid：CSS Gridを使った実装~~ #153 
- ~~Flex：Flexbox化Layout Classの追加~~ #171 
- ~~Flex：ファイルをUtilityからLayoutに移動~~ #188
- ~~Form：Inputへのアイコン設置機能を追加~~ #191 
- ~~Form：内側シャドウ・枠線をClassで分離~~ #192
- ~~Form：Multiple Selectに選択済み背景色を追加~~ #206

## Migration

- v6.6.0 → v7.0.0-alpha.42 #238

---

## Update

### Total

- [x] Storybookの導入 #227
- [x] CSSの配布ディレクトリをdocsからdistに変更 #229
- [x] CSSの配布用ビルドをgulpからnpm-scriptsに変更 #236
- [x] Mixinを使ったSCSSの転用機能を追加 #226
- [x] セレクターのカスタマイズ機能を追加 #228
- [x] SCSSの単純化 #240
- [x] SCSSの構造変更 #239
- [x] SCSSの依存ファイルを内包して管理 #237
- [x] SCSSカスタマイズの再設計 #163 
- [x] SCSSで出力管理・デフォルトの最小限化 #201

### Addition

- none

### Change

- [x] Section：Inner VWの廃止 #241

## Cancelled

- ~~Radius：角丸を付与するUtilityを追加~~ #242

## Migration

- v6.6.0 → v7.0.0 #234
- v7.0.0-alpha.42 → v7.0.0 #235

**Comment by qrac** [comment]
releaseに移行。
